In [ ]:
# Diabetic Prediction in India

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

dataframe = pd.read_csv("diabetes_prediction_india.csv")
dataframe

,Age,Gender,BMI,Family_History,Physical_Activity,Diet_Type,Smoking_Status,Alcohol_Intake,Stress_Level,Hypertension,...,Health_Insurance,Regular_Checkups,Medication_For_Chronic_Conditions,Pregnancies,Polycystic_Ovary_Syndrome,Glucose_Tolerance_Test_Result,Vitamin_D_Level,C_Protein_Level,Thyroid_Condition,Diabetes_Status
0,48,Male,35.5,No,High,Non-Vegetarian,Never,NaN,Medium,Yes,...,No,No,No,0,0,124.3,31.5,7.46,Yes,Yes
1,18,Other,28.7,Yes,Medium,Non-Vegetarian,Current,Moderate,High,No,...,Yes,Yes,No,0,0,151.4,12.5,5.64,Yes,No
2,21,Other,30.0,Yes,High,Non-Vegetarian,Current,Moderate,High,Yes,...,No,No,Yes,0,0,106.1,35.8,7.20,No,Yes
3,25,Female,25.6,No,Medium,Vegetarian,Former,Moderate,High,Yes,...,No,No,Yes,1,No,85.6,15.4,6.53,Yes,No
4,78,Male,38.8,No,High,Non-Vegetarian,Current,High,High,No,...,No,No,Yes,0,0,77.0,28.6,0.58,No,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5287,35,Male,39.0,No,High,Vegan,Never,Moderate,Low,Yes,...,Yes,No,Yes,0,0,174.6,16.3,5.48,Yes,No
5288,44,Other,32.0,Yes,Low,Vegetarian,Never,Moderate,High,Yes,...,Yes,Yes,No,0,0,119.3,32.4,7.39,Yes,Yes
5289,55,Male,22.3,No,High,Non-Vegetarian,Current,NaN,Low,Yes,...,No,No,Yes,0,0,143.6,43.3,7.24,Yes,Yes
5290,65,Other,21.7,Yes,High,Non-Vegetarian,Former,NaN,Low,Yes,...,No,No,Yes,0,0,79.8,22.2,4.00,No,Yes
5291,56,Female,19.0,Yes,Low,Non-Vegetarian,Never,High,Medium,Yes,...,Yes,Yes,Yes,1,Yes,92.6,13.5,4.54,Yes,Yes

In [6]:
dataframe.head(10)

,Age,Gender,BMI,Family_History,Physical_Activity,Diet_Type,Smoking_Status,Alcohol_Intake,Stress_Level,Hypertension,...,Health_Insurance,Regular_Checkups,Medication_For_Chronic_Conditions,Pregnancies,Polycystic_Ovary_Syndrome,Glucose_Tolerance_Test_Result,Vitamin_D_Level,C_Protein_Level,Thyroid_Condition,Diabetes_Status
0,48,Male,35.5,No,High,Non-Vegetarian,Never,NaN,Medium,Yes,...,No,No,No,0,0,124.3,31.5,7.46,Yes,Yes
1,18,Other,28.7,Yes,Medium,Non-Vegetarian,Current,Moderate,High,No,...,Yes,Yes,No,0,0,151.4,12.5,5.64,Yes,No
2,21,Other,30.0,Yes,High,Non-Vegetarian,Current,Moderate,High,Yes,...,No,No,Yes,0,0,106.1,35.8,7.20,No,Yes
3,25,Female,25.6,No,Medium,Vegetarian,Former,Moderate,High,Yes,...,No,No,Yes,1,No,85.6,15.4,6.53,Yes,No
4,78,Male,38.8,No,High,Non-Vegetarian,Current,High,High,No,...,No,No,Yes,0,0,77.0,28.6,0.58,No,Yes
5,60,Male,19.2,No,High,Vegetarian,Current,NaN,Low,No,...,No,Yes,Yes,0,0,180.2,49.0,1.83,No,No
6,38,Female,36.4,Yes,Medium,Vegetarian,Current,High,Medium,No,...,Yes,No,Yes,2,No,78.6,11.7,8.24,Yes,No
7,23,Other,21.4,No,Medium,Vegan,Never,NaN,Low,No,...,Yes,Yes,Yes,0,0,140.6,25.8,3.39,Yes,No
8,22,Female,18.9,No,Medium,Vegan,Former,NaN,Medium,Yes,...,Yes,Yes,Yes,0,No,87.5,18.4,3.86,No,No
9,18,Female,24.4,No,Low,Vegetarian,Never,NaN,Medium,Yes,...,Yes,Yes,No,9,Yes,157.2,23.6,2.16,Yes,Yes

In [7]:
dataframe.tail(10)

,Age,Gender,BMI,Family_History,Physical_Activity,Diet_Type,Smoking_Status,Alcohol_Intake,Stress_Level,Hypertension,...,Health_Insurance,Regular_Checkups,Medication_For_Chronic_Conditions,Pregnancies,Polycystic_Ovary_Syndrome,Glucose_Tolerance_Test_Result,Vitamin_D_Level,C_Protein_Level,Thyroid_Condition,Diabetes_Status
5282,31,Male,23.2,No,High,Vegetarian,Current,High,Low,Yes,...,No,Yes,No,0,0,127.5,26.6,4.63,Yes,Yes
5283,70,Male,37.8,Yes,Low,Vegetarian,Former,Moderate,Medium,Yes,...,No,No,Yes,0,0,142.6,36.8,1.81,No,Yes
5284,60,Other,17.3,No,Medium,Non-Vegetarian,Former,Moderate,Low,Yes,...,No,Yes,Yes,0,0,180.2,49.0,9.06,No,Yes
5285,72,Female,27.0,Yes,Medium,Vegetarian,Current,NaN,High,Yes,...,Yes,No,No,0,Yes,128.6,15.0,3.16,No,No
5286,72,Other,36.7,Yes,Medium,Non-Vegetarian,Current,Moderate,Low,Yes,...,Yes,Yes,Yes,0,0,135.1,12.6,5.07,Yes,Yes
5287,35,Male,39.0,No,High,Vegan,Never,Moderate,Low,Yes,...,Yes,No,Yes,0,0,174.6,16.3,5.48,Yes,No
5288,44,Other,32.0,Yes,Low,Vegetarian,Never,Moderate,High,Yes,...,Yes,Yes,No,0,0,119.3,32.4,7.39,Yes,Yes
5289,55,Male,22.3,No,High,Non-Vegetarian,Current,NaN,Low,Yes,...,No,No,Yes,0,0,143.6,43.3,7.24,Yes,Yes
5290,65,Other,21.7,Yes,High,Non-Vegetarian,Former,NaN,Low,Yes,...,No,No,Yes,0,0,79.8,22.2,4.00,No,Yes
5291,56,Female,19.0,Yes,Low,Non-Vegetarian,Never,High,Medium,Yes,...,Yes,Yes,Yes,1,Yes,92.6,13.5,4.54,Yes,Yes

In [8]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5292 entries, 0 to 5291
Data columns (total 27 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                5292 non-null   int64
 1   Gender                             5292 non-null   object
 2   BMI                                5292 non-null   float64
 3   Family_History                     5292 non-null   object
 4   Physical_Activity                  5292 non-null   object
 5   Diet_Type                          5292 non-null   object
 6   Smoking_Status                     5292 non-null   object
 7   Alcohol_Intake                     3512 non-null   object
 8   Stress_Level                       5292 non-null   object
 9   Hypertension                       5292 non-null   object
 10  Cholesterol_Level                  5292 non-null   float64
 11  Fasting_Blood_Sugar                5292 non-null   float64
 12  Postprandial_Blood_Sugar           5292 non-null   float64
 13  HBA1C                              5292 non-null   float64
 14  Heart_Rate                         5292 non-null   int64
 15  Waist_Hip_Ratio                    5292 non-null   float64
 16  Urban_Rural                        5292 non-null   object
 17  Health_Insurance                   5292 non-null   object
 18  Regular_Checkups                   5292 non-null   object
 19  Medication_For_Chronic_Conditions  5292 non-null   object
 20  Pregnancies                        5292 non-null   int64
 21  Polycystic_Ovary_Syndrome          5292 non-null   object
 22  Glucose_Tolerance_Test_Result      5292 non-null   float64
 23  Vitamin_D_Level                    5292 non-null   float64
 24  C_Protein_Level                    5292 non-null   float64
 25  Thyroid_Condition                  5292 non-null   object
 26  Diabetes_Status                    5292 non-null   object
dtypes: float64(9), int64(3), object(15)
memory usage: 1.1+ MB

In [11]:
dataframe.shape

(5292, 27)

In [12]:
dataframe.describe()

,Age,BMI,Cholesterol_Level,Fasting_Blood_Sugar,Postprandial_Blood_Sugar,HBA1C,Heart_Rate,Waist_Hip_Ratio,Pregnancies,Glucose_Tolerance_Test_Result,Vitamin_D_Level,C_Protein_Level
count,5292.000000,5292.000000,5292.000000,5292.000000,5292.000000,5292.000000,5292.000000,5292.000000,5292.000000,5292.000000,5292.000000,5292.000000
mean,48.417989,27.459883,199.777098,124.940193,164.709902,8.226909,89.787415,0.949399,1.493386,135.011867,29.909883,5.258743
std,18.040544,7.194187,57.103759,32.091770,43.152803,2.179662,17.238430,0.144871,2.677414,37.541696,11.527951,2.754500
min,18.000000,15.000000,100.000000,70.000000,90.100000,4.500000,60.000000,0.700000,0.000000,70.100000,10.000000,0.500000
25%,33.000000,21.200000,151.100000,97.100000,128.175000,6.300000,75.000000,0.820000,0.000000,102.175000,20.000000,2.880000
50%,48.000000,27.400000,198.600000,124.050000,164.950000,8.200000,90.000000,0.950000,0.000000,136.000000,29.800000,5.270000
75%,64.000000,33.600000,249.100000,153.300000,201.000000,10.100000,105.000000,1.080000,2.000000,167.100000,39.900000,7.660000
max,79.000000,40.000000,300.000000,180.000000,240.000000,12.000000,119.000000,1.200000,9.000000,200.000000,50.000000,10.000000

In [13]:
dataframe.values

array([[48, 'Male', 35.5, ..., 7.46, 'Yes', 'Yes'],
       [18, 'Other', 28.7, ..., 5.64, 'Yes', 'No'],
       [21, 'Other', 30.0, ..., 7.2, 'No', 'Yes'],
       ...,
       [55, 'Male', 22.3, ..., 7.24, 'Yes', 'Yes'],
       [65, 'Other', 21.7, ..., 4.0, 'No', 'Yes'],
       [56, 'Female', 19.0, ..., 4.54, 'Yes', 'Yes']],
      shape=(5292, 27), dtype=object)

In [14]:
dataframe.columns

Index(['Age', 'Gender', 'BMI', 'Family_History', 'Physical_Activity',
       'Diet_Type', 'Smoking_Status', 'Alcohol_Intake', 'Stress_Level',
       'Hypertension', 'Cholesterol_Level', 'Fasting_Blood_Sugar',
       'Postprandial_Blood_Sugar', 'HBA1C', 'Heart_Rate', 'Waist_Hip_Ratio',
       'Urban_Rural', 'Health_Insurance', 'Regular_Checkups',
       'Medication_For_Chronic_Conditions', 'Pregnancies',
       'Polycystic_Ovary_Syndrome', 'Glucose_Tolerance_Test_Result',
       'Vitamin_D_Level', 'C_Protein_Level', 'Thyroid_Condition',
       'Diabetes_Status'],
      dtype='object')

In [ ]:
dataframe.index

RangeIndex(start=0, stop=5292, step=1)

In [20]:
if dataframe['Alcohol_Intake'].isnull().any():
    dataframe